In [ ]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy, short for Numerical Python, is a powerful library that plays a crucial role in scientific computing and data analysis with Python. 
Purpose of NumPy:
* Efficient Array Operations: NumPy provides a high-performance multidimensional array object, called ndarray, which allows for efficient   storage and manipulation of numerical data.
* Mathematical Functions: It includes a vast collection of mathematical functions that operate on arrays, enabling complex calculations and data manipulations.
* Linear Algebra Support: NumPy includes functionalities for linear algebra operations, such as matrix multiplication, eigenvalue problems, and other advanced mathematical computations.
* Random Number Generation: It offers tools for generating random numbers and performing statistical operations.
* Integration with Other Libraries: NumPy serves as the foundational package for many other scientific libraries, such as SciPy, pandas, and Matplotlib, facilitating a cohesive ecosystem for data analysis and scientific computing.

Advantages of NumPy:
* Performance: NumPy operations are implemented in C and Fortran, making them significantly faster than equivalent operations in standard Python lists. This speed is particularly beneficial for large datasets.
* Memory Efficiency: The ndarray is more memory-efficient than Python lists because it stores elements of the same data type, leading to optimized data storage.
* Vectorization: NumPy allows for vectorized operations, enabling users to perform element-wise operations without writing explicit loops. This leads to cleaner and more readable code.
* Broadcasting: NumPy can perform operations on arrays of different shapes through broadcasting, allowing for more flexibility in calculations without requiring manual manipulation of array shapes.
* Extensive Functionality: The library supports a wide range of mathematical and statistical functions, making it versatile for various applications in science, engineering, and data analysis.
* Interoperability: NumPy arrays can easily interface with other libraries and tools in the Python ecosystem, promoting seamless integration for more complex workflows.
* Enhancing Python’s Capabilities

NumPy enhances Python's capabilities for numerical operations by:
* Providing a robust framework for handling large datasets efficiently.
* Allowing complex mathematical operations with minimal code and better readability.
* Enabling high-performance computations that are crucial for scientific research and data analysis.

In [ ]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Both np.mean() and np.average() are functions in NumPy used to compute the central tendency of data, but they have distinct functionalities and use cases. Here’s a comparison:
np.mean()
Purpose: Computes the arithmetic mean of an array along a specified axis.
Parameters:
a: Input array.
axis: Axis or axes along which the means are computed.
dtype: Data type to use for the output.
out: Alternative output array.
keepdims: If set to True, the reduced axes are left in the result as dimensions with size one.
Default Behavior: Calculates the mean of all elements if no axis is specified.

np.average()
Purpose: Computes the weighted average of an array, which can be adjusted by providing weights.
Syntax: np.average(a, axis=None, weights=None, returned=False)
Parameters:
a: Input array.
axis: Axis or axes along which the averages are computed.
weights: Weights associated with the values in a. If not specified, all values are assumed to have equal weight.
returned: If set to True, returns a tuple of the average and the sum of the weights.
Default Behavior: Calculates the simple average (equivalent to np.mean()) if no weights are specified.

Key Differences
Weights:
np.mean(): Does not take weights into account. All values are treated equally.
np.average(): Allows for weights, making it suitable for scenarios where different values contribute differently to the average.
Use Cases:

Use np.mean() when you need the simple arithmetic mean of an array without any weighting considerations.
Use np.average() when you need to calculate a weighted average, such as in statistical analysis where certain data points have different levels of importance.

In [ ]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Reversing a NumPy array can be done using slicing techniques along different axes.
1D Array: Use slicing [::-1] to reverse the entire array.
2D Array:
Use [::-1, :] to reverse rows.
Use [:, ::-1] to reverse columns.
Use [::-1, ::-1] to reverse both rows and columns.
These slicing techniques provide a straightforward and efficient way to reverse arrays in NumPy.

In [1]:
# Example for 1D array:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_1d = array_1d[::-1]

print("Original 1D array:", array_1d)
print("Reversed 1D array:", reversed_1d)


Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


In [2]:
# Example for 2D array.
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Reverse along axis 0 (rows)
reversed_axis_0 = array_2d[::-1, :]
print("Reversed along axis 0 (rows):")
print(reversed_axis_0)

# Reverse along axis 1 (columns)
reversed_axis_1 = array_2d[:, ::-1]
print("\nReversed along axis 1 (columns):")
print(reversed_axis_1)

# Reverse along both axes
reversed_both_axes = array_2d[::-1, ::-1]
print("\nReversed along both axes:")
print(reversed_both_axes)

Reversed along axis 0 (rows):
[[7 8 9]
 [4 5 6]
 [1 2 3]]

Reversed along axis 1 (columns):
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Reversed along both axes:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

To determine the data type of elements in a NumPy array, we can use the .dtype attribute of the array. This attribute provides information about the data type of the elements stored in the array.

Importance of Data Types:
1. Memory Management:
Different data types consume different amounts of memory. For example, an integer may take up 4 or 8 bytes (depending on the system), while a float usually takes up 8 bytes. Using the appropriate data type can significantly reduce memory usage, especially with large datasets.
Choosing a smaller data type (like np.int8 instead of np.int64) can save memory but should be done with care to avoid overflow.
2. Performance:
Operations on NumPy arrays are optimized for specific data types. Using the correct type can enhance performance by allowing the underlying libraries (like BLAS or LAPACK) to use optimized routines.
For example, operations on integer arrays may be faster than operations on floating-point arrays due to the simplicity of integer arithmetic.
3.Numerical Precision:
Different data types provide different levels of precision. For instance, float32 has lower precision compared to float64. Choosing the right type is crucial in applications that require high numerical precision, like scientific computing and machine learning.
4. Type Safety:
Knowing the data type can help prevent errors. For instance, if you expect an array of integers but receive an array of strings, it can lead to runtime errors or unexpected behavior in calculations.

In [3]:
#Example for checking data type
import numpy as np

# Create a NumPy array with integer data type
array_int = np.array([1, 2, 3, 4])
print("Data type of array_int:", array_int.dtype)

# Create a NumPy array with floating-point data type
array_float = np.array([1.0, 2.0, 3.0])
print("Data type of array_float:", array_float.dtype)

# Create a NumPy array with complex data type
array_complex = np.array([1 + 2j, 3 + 4j])
print("Data type of array_complex:", array_complex.dtype)


Data type of array_int: int32
Data type of array_float: float64
Data type of array_complex: complex128


In [ ]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

An ndarray is a powerful N-dimensional array object that allows you to store and operate on large datasets in a vectorized manner. Each array has a shape, which defines its dimensions, and a data type, which specifies the type of elements it can hold.

Key Features of ndarrays
* Multidimensional: ndarrays can have any number of dimensions (1D, 2D, 3D, etc.), allowing for complex data representations.
* Homogeneous Data: All elements in an ndarray must be of the same data type (e.g., all integers or all floats), leading to more efficient storage and operations.
* Contiguous Memory Layout: ndarrays store data in contiguous blocks of memory, which enhances performance for numerical computations due to better cache utilization.
* Broadcasting: NumPy supports broadcasting, which allows for arithmetic operations on arrays of different shapes without needing to manually adjust their sizes.
* Vectorized Operations: You can perform element-wise operations on ndarrays without explicit loops, leading to cleaner code and faster execution.
* Rich Functionality: NumPy provides a wide array of built-in functions for mathematical operations, statistical analyses, linear algebra, and more, all optimized for ndarrays.
* Indexing and Slicing: ndarrays support advanced indexing and slicing techniques, enabling you to extract or modify subarrays efficiently.

Differences Between ndarrays and Python Lists
Data Type Consistency:
ndarrays: Homogeneous; all elements must be of the same data type.
Lists: Heterogeneous; can contain elements of different types (e.g., integers, floats, strings).
Performance:
ndarrays: More memory-efficient and faster for numerical computations due to optimized storage and operations.
Lists: Slower for numerical operations, as they require element-wise processing through Python loops.
Functionality:
ndarrays: Comes with a comprehensive set of mathematical functions and methods for array manipulation.
Lists: Limited to built-in Python methods; no specialized numerical functions.
Memory Usage:
ndarrays: Uses less memory for large datasets due to homogeneous storage and efficient data types.
Lists: Can be less efficient, as each element has additional overhead to store type information.
Array Operations:
ndarrays: Supports vectorized operations (e.g., element-wise addition) directly.
Lists: Requires explicit loops for similar operations, which can be less readable and slower.

In [ ]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays offer several significant performance benefits over standard Python lists, particularly when it comes to large-scale numerical operations.
1. Memory Efficiency:
* Contiguous Memory Storage: NumPy arrays are stored in contiguous blocks of memory, which minimizes overhead and improves data locality. This is more efficient than Python lists, which store references to objects scattered in memory. Contiguous storage enables better cache utilization by the CPU, leading to faster access times.
* Homogeneous Data Types: All elements in a NumPy array must be of the same type, allowing for optimized memory allocation. In contrast, Python lists can store different types, which incurs additional memory overhead for type information.
2. Speed of Operations
Vectorized Operations: NumPy allows for element-wise operations to be performed directly on arrays without the need for explicit loops in Python. This vectorization leverages highly optimized C and Fortran libraries under the hood, resulting in significant speed improvements. In contrast, operations on Python lists require iteration through each element, which can be slow for large datasets.
Optimized Mathematical Functions
Built-in Functions: NumPy provides a comprehensive set of optimized mathematical functions (e.g., np.sum, np.mean, np.dot) that operate directly on arrays. These functions are implemented in C and can perform operations faster than equivalent Python functions applied to lists.
4. Broadcasting
Flexible Operations: NumPy’s broadcasting feature allows operations between arrays of different shapes without requiring explicit resizing. This capability can simplify code and enhance performance by avoiding the overhead of creating new arrays.
5. Reduced Overhead
Minimal Type Checks: NumPy arrays benefit from minimal type checking and overhead during operations, as the data type is fixed. In contrast, Python lists perform dynamic type checking, which can slow down operations.
6. Parallel Processing and Optimization
Integration with Libraries: NumPy integrates seamlessly with optimized libraries such as BLAS and LAPACK, which can perform linear algebra operations in parallel. This leads to faster computations for operations like matrix multiplication or solving systems of equations compared to using nested loops with Python lists.

In [ ]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

The vstack() and hstack() functions in NumPy are used for stacking arrays vertically and horizontally, respectively. 
vstack(): 
Purpose: Stacks arrays in sequence vertically (row-wise).
Input: Arrays to be stacked must have the same shape along all but the first axis

In [4]:
# Example for vstack()
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Stack arrays vertically
vstacked = np.vstack((array1, array2))

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nVertically stacked array:")
print(vstacked)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Vertically stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


hstack():
Purpose: Stacks arrays in sequence horizontally (column-wise).
Input: Arrays to be stacked must have the same shape along all but the second axis.

In [5]:
# Example of hstack()
# Create two 2D arrays
array3 = np.array([[1, 2],
                   [3, 4]])

array4 = np.array([[5, 6],
                   [7, 8]])

# Stack arrays horizontally
hstacked = np.hstack((array3, array4))

print("Array 3:")
print(array3)

print("\nArray 4:")
print(array4)

print("\nHorizontally stacked array:")
print(hstacked)


Array 3:
[[1 2]
 [3 4]]

Array 4:
[[5 6]
 [7 8]]

Horizontally stacked array:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions

In NumPy, the fliplr() and flipud() functions are used to flip arrays along different axes.
Differences
* Direction of Flip:
fliplr(): Flips the array horizontally (left to right).
flipud(): Flips the array vertically (up to down).
* Effect on Array:
fliplr(): Reverses the order of elements in each row.
flipud(): Reverses the order of elements in each column.
* Dimensionality:B
Both functions primarily operate on 2D arrays but can also work on higher-dimensional arrays, treating each 2D slice independently.
fliplr(): 
Purpose: Flips an array left to right (horizontally).
Effect: The order of elements in each row is reversed.
Applicable Dimensions: Primarily operates on 2D arrays, but it can be used on higher-dimensional arrays as well, treating each 2D slice along the first axis independently.

In [6]:
# Example of fliplr()
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flip the array left to right
flipped_lr = np.fliplr(array_2d)

print("Original array:")
print(array_2d)

print("\nFlipped left to right (fliplr):")
print(flipped_lr)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped left to right (fliplr):
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
flipud()
Purpose: Flips an array up to down (vertically).
Effect: The order of elements in each column is reversed.
Applicable Dimensions: Similar to fliplr(), it primarily works on 2D arrays but can also be used on higher-dimensional arrays.

In [7]:
# Example of flipud()
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flip the array up to down
flipped_ud = np.flipud(array_2d)

print("Original array:")
print(array_2d)

print("\nFlipped up to down (flipud):")
print(flipped_ud)



Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped up to down (flipud):
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into multiple sub-arrays. It provides more flexibility than the split() method, especially when the array size is not perfectly divisible by the specified number of splits.
unctionality of array_split()
Purpose: To divide an array into multiple sub-arrays along a specified axis.
Input Parameters:
ary: The input array to be split.
indices_or_sections: This can be an integer or a list. If it’s an integer, it specifies the number of equal-sized sub-arrays to return. If it’s a list, it defines the specific indices at which to split the array.
axis: The axis along which to split the array (default is 0, which is the first axis).

In [8]:
# Example for array_split
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 3 equal parts
split_arrays = np.array_split(array, 3)

print("Original array:", array)
print("Split arrays:")
for sub_array in split_arrays:
    print(sub_array)


Original array: [1 2 3 4 5 6]
Split arrays:
[1 2]
[3 4]
[5 6]


Handling Uneven Splits:
When the array size is not evenly divisible by the number of desired splits, array_split() handles this by distributing the remaining elements across the resulting sub-arrays. The extra elements are distributed one by one to the first few sub-arrays until all elements are accounted for.

In [9]:
# Example for Uneven splits
# Split the array into 4 parts (uneven split)
uneven_split_arrays = np.array_split(array, 4)

print("Original array:", array)
print("Unevenly split arrays:")
for sub_array in uneven_split_arrays:
    print(sub_array)


Original array: [1 2 3 4 5 6]
Unevenly split arrays:
[1 2]
[3 4]
[5]
[6]


In [ ]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

vectorization refers to the ability to perform operations on entire arrays (or large chunks of data) at once, rather than using explicit loops to iterate over individual elements. This takes advantage of NumPy's underlying optimizations, which leverage low-level implementations (like C and Fortran) to execute operations in a highly efficient manner.

Benefits:
* Performance Improvement: Vectorized operations can be significantly faster than their loop-based counterparts because they minimize the overhead of Python's interpreted loops.
* Cleaner Code: Vectorization leads to more concise and readable code, making it easier to understand and maintain. 
Broadcasting
Definition: Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes. When operating on two arrays, NumPy will automatically "stretch" the smaller array across the larger one so that they have compatible shapes.

How it Works:
Shape Compatibility: Two arrays are compatible for broadcasting if:
They have the same number of dimensions.
The size of each dimension is either the same or one of them is 1.
Stretching: The smaller array is virtually expanded to match the shape of the larger array during the operation.
Benefits:
Flexibility: Broadcasting allows for operations on arrays of different shapes without requiring explicit reshaping or tiling of data.
Performance: It avoids the need for copying data or using loops, which can improve computational efficiency.

In [ ]:
# 11. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [12]:
import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array)

# Step 2: Interchange rows and columns
transposed_array = np.transpose(array)
# or alternatively
# transposed_array = array.T

print("\nTransposed array (interchanged rows and columns):")
print(transposed_array)


Original array:
[[ 9 41 10]
 [44 47 52]
 [75 79 24]]

Transposed array (interchanged rows and columns):
[[ 9 44 75]
 [41 47 79]
 [10 52 24]]


In [ ]:
# 12. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [13]:
import numpy as np

# Step 1: Generate a 1D array with 10 elements
array_1d = np.arange(10)  # Creates an array with elements [0, 1, 2, ..., 9]
print("Original 1D array:")
print(array_1d)

# Step 2: Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 array:")
print(array_2x5)

# Step 3: Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into 5x2 array:")
print(array_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# 13. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [14]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 array:")
print(array_4x4)

# Step 2: Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 array with a border of zeros:")
print(array_with_border)


Original 4x4 array:
[[0.65892424 0.39326045 0.20903659 0.10914687]
 [0.5937082  0.1087472  0.80043246 0.56228817]
 [0.1796384  0.66828956 0.59771421 0.39421612]
 [0.29987918 0.64809006 0.45718142 0.77414145]]

6x6 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.65892424 0.39326045 0.20903659 0.10914687 0.        ]
 [0.         0.5937082  0.1087472  0.80043246 0.56228817 0.        ]
 [0.         0.1796384  0.66828956 0.59771421 0.39421612 0.        ]
 [0.         0.29987918 0.64809006 0.45718142 0.77414145 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
# 14. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [15]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
# 15. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [16]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array)
lowercase = np.char.lower(array)
titlecase = np.char.title(array)
capitalize = np.char.capitalize(array)

# Print the results
print("Original array:")
print(array)

print("\nUppercase:")
print(uppercase)

print("\nLowercase:")
print(lowercase)

print("\nTitle case:")
print(titlecase)

print("\nCapitalized:")
print(capitalize)


Original array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


In [ ]:
# 16. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [17]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

print("Original array of words:")
print(words_array)

print("\nWords with spaces between characters:")
print(spaced_words)


Original array of words:
['python' 'numpy' 'pandas']

Words with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [ ]:
# 17. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [18]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
# 18. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [19]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [ ]:
# 19. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [20]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Step 2: Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Step 3: Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display results
print("Random integers:")
print(random_integers)

print("\nPrime numbers in the array:")
print(prime_numbers)


Random integers:
[ 26 812 524 997 570 440 622 608 603 786 742 513 911 771  17 851 261 718
 316 324 654  96 546 776 209 717 492 887 515 507 404 599 653  11 690 945
 999 949 146 477 297 817 815 766 239  28 653 217 808 203 816 832 362 372
 782  27   3 535  25 750 939  96 568  77 680 962  71 971 312 501 185 830
 241 165 702 412 994 955 885 185 967 433 366  18 668 668 205  13 625 778
 489 546  91 199  29 130 804 564 600 300]

Prime numbers in the array:
[997, 911, 17, 887, 599, 653, 11, 239, 653, 3, 71, 971, 241, 967, 433, 13, 199, 29]


In [ ]:
# 20. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [22]:
import numpy as np

# Step 1: Create a NumPy array representing daily temperatures for a month (30 days)
# For example, let's generate random temperatures between 15 and 30 degrees Celsius
daily_temperatures = np.random.randint(15, 31, size=30)

print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Step 2: Reshape the array into a 2D array (5 weeks)
weekly_temperatures = daily_temperatures.reshape(5, 6)  # 5 weeks, 6 days each

# Step 3: Calculate the average temperature for each week
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display results
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[28 28 29 23 18 21 23 30 27 23 18 16 18 23 16 26 27 18 16 29 30 27 15 26
 17 19 30 19 20 20]

Weekly Averages:
[24.5        22.83333333 21.33333333 23.83333333 20.83333333]
